# Site settings
title: Karla Medina
email: kmedina@albany.edu
description: Karla is an INF major graduating in 2015.
url: http://kmedina.github.io
github_username: kmedina

# Build settings
markdown: kramdown
permalink: pretty
