# Site settings
title: Karla Medina
email: brightest.day25@gmail.com
description: Karla is an INF major graduate in 2015.
url: http://kmedina.github.io
github_username: kmedina

# Build settings
markdown: kramdown
permalink: pretty
